name: Lint All Projects

on:
  pull_request:
    branches: [main, develop, feat/add-github-actions]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Asegúrate de usar la versión de Node.js que se adapte a tu proyecto
      - name: Install Dependencies
        run: npm install
      - name: Run Lint on All Projects
        run: npx nx run-many --target=lint --all
        # npx nx run-many --target=lint --all ejecuta el linting en todos los proyectos definidos en workspace.json/angular.json
