name: Lint All Projects

on:
  pull_request:
    branches: [main, develop, feat/add-github-actions]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install Dependencies
        run: npm install nx eslint @typescript-eslint/parser @typescript-eslint/eslint-plugin eslint-config-airbnb-typescript eslint-config-prettier eslint-plugin-import eslint-plugin-prettier
      - name: Run Lint on All Projects
        run: npx nx run-many --target=lint --all
