name: Format Code

on:
  push:
    branches: [ main, develop, feat/add-github-actions ]
  pull_request:
    branches: [ main, develop, feat/add-github-actions ]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'

    - name: Install Prettier
      run: npm install --save-dev prettier

    - name: Run Prettier
      run: npx prettier --write .

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Apply Prettier" || echo "No changes to commit"
        git status
        if [[ `git status --porcelain` ]]; then
          git push origin HEAD:${{ github.head_ref }}
        else
          echo "No changes to commit*"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

